# SITE SETUP
# Guide: https://docs.hugoblox.com/tutorial/
# Documentation: https://docs.hugoblox.com/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

params:
  featured_pdf: "featured.pdf"    # Specify the default PDF name
  prioritize_pdf: true            # Enable PDF priority globally

# Appearance
appearance:
  mode: system
  color: emerald

# SEO
marketing:
  seo:
    site_type: Person
    local_business_type: "Educational Institution"
    org_name: "University of Cambridge"
    description: "Richard Bergna's academic website showcasing research in uncertainty quantification, deep learning, and probabilistic machine learning."
    twitter: "RichardBergna"
  analytics:
    google_analytics: "UA-XXXXX-Y"  # Replace with your Google Analytics ID if applicable
  verification:
    google: ""
    baidu: ""

# Site header
header:
  navbar:
    enable: true
    blox: "navbar"
    fixed_to_top: true
    show_search: true
    show_theme_chooser: true
    logo:
      text: "Richard Bergna"

# Site footer
footer:
  copyright:
    notice: "© {year} Richard Bergna. This work is licensed under {license}"
    license:
      enable: true
      allow_derivatives: false
      share_alike: true
      allow_commercial: false

# Localization
locale:
  date_format: "Jan 2, 2006"
  time_format: "3:04 PM"

# Site features
features:
  math:
    enable: true
  privacy_pack:
    enable: false
